### ISSUE TITLE
혼자연습하기 Checklist DB화

### ISSUE THREAD

**Issue by sjh2428** [Yapp-17th/Web_2_Backend#24]

**Comment by MoonYeeun** [comment]
체크리스트 부분도 만들어야하는데 이 부분은 db화를 어케 시켜야할지 감이 안잡히네요 😰

**Comment by sjh2428** [comment]
흠,, 그러게요 ㅠ

음 그냥 체크 유무를 하나의 컬럼으로 하고 String 파싱하는건 어떤가요? ㅋㅋ

테이블로 풀어서 하면 조인이 많이 들어갈 거 같아서 성능 저하가 조큼 심할 것 같은 느낌이네요 🤔
