### ISSUE TITLE
DTO -> Entity 변환 의논

### ISSUE THREAD

**Issue by sjh2428** [Yapp-17th/Web_2_Backend#6]
entity의 값을 update 할 때

보통 Node.js + Express + Sequelize 사용시
```js
entity = { ...entity, ...dto };
```
이런 느낌으로 사용하던 것으로 알고 있는데(물론 DTO 멤버변수 이름과 엔티티 멤버변수 이름을 같게 구현하지 않습니다),

Java에서도 위와 같은 느낌으로 해줄 수 있는 방법이 있을까요?

```java
@PostMapping(consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
public ResponseEntity<?> make(@RequestBody @Valid MakeDTO.Request dto, BindingResult result) {
    if (result.hasErrors()) {
        ErrorResponse errorResponse = ErrorResponse.of(ErrorCode.INVALID_INPUT_VALUE);
        return new ResponseEntity<>(errorResponse, HttpStatus.BAD_REQUEST);
    }
    Entity e = new Entity(dto.name, dto.priority, dto.hi);
    entityRepository.save(e);
    return new ResponseEntity<>(modelMapper.map(e, MakeDTO.Response.class), HttpStatus.CREATED);
  }
```

위와 같이 entity를 새로 만들어주게 될 때 dto의 모든 값을 직접 풀어서 값을 넣어주는 것만 알고 있는데, 위 방법 말고(modelMapper도 빼고)

```js
Entity e = new Entity(...dto);

// or

Entity e = new Entity();
Object.entries(dto).forEach(([k, v]) => {
  e[k] = v
});
```

JS에서 spread 연산자 또는 Object entries로 풀어서 키 값에 value를 넣는 것처럼 할 수 있는 방법을 찾고 싶습니다..!

**Comment by MoonYeeun** [comment]
java가 JS처럼 유연한 언어가 아니라 Object 안의 값들을 풀어서 사용할 수 있을까요....ㅠㅠ
Object 배열이나 컬렉션이면 stream을 쓰면 될텐데 Object 자체는 모르겠네요...허허
현재로써는 생각나는게 없긴한데 한번 찾아볼게용

**Comment by sjh2428** [comment]
안되면 어쩔 수 없기는 한데 ㅜㅜ 엔티티가 한번 정해지면 거의 바뀔일이 없기는 한데..!

혹시 있거나 좋은 아이디어가 떠오르신다면 말씀해주세요! :D

**Comment by Lavegaa** [comment]
https://stackoverflow.com/questions/46388620/java-spread-operator
이런 글이 있는데 라이브러리를 활용해서 비슷하게 구현은 하네요! 적당할지는 모르겠네요 ㅠㅠ
