### ISSUE TITLE
DB스키마 질문

### ISSUE THREAD

**Issue by Lavegaa** [Yapp-17th/Web_2_Backend#7]
안녕하세요~ DB스키마 보다가 궁금한 점 있어서 이슈 남깁니다.

## tbl_study_feedback
여기에서 target이 되는 사람은 있는데 혹시 피드백을 남기는 사람은 저장이 안되는건가요? 피드백이 익명으로 들어가는건지 궁금합니다.

##  tbl_study_room & tbl_study_room_participant
방의 id와 이를 매핑애서 참가자 테이블이 있는 것 같은데 tbl_study_room에 있는 user는 방장이 되는건가요? 그렇다면 방장은 참가자 테이블에도 중복되서 들어가는지 궁금합니다. 

그리고 디자인을 보면 방마다 제목 이외에도 설명(ex: 네이버 기술면접 준비하는 방이에요~)이 들어있는데 description컬럼이 하나 들어가면 좋을 것 같아요.

**Comment by sjh2428** [comment]
> ## tbl_study_feedback
> 여기에서 target이 되는 사람은 있는데 혹시 피드백을 남기는 사람은 저장이 안되는건가요? 피드백이 익명으로 들어가는건지 궁금합니다.
- 넵 익명으로 들어가는 것으로 생각하고는 있습니다. 누구의 피드백인지 알 필요가 있을까? 라는 생각도 들었고 누구의 피드백인지도 함께 들어간다면 100%의 피드백을 줄 것을 7-80%만 줄 수 있지 않을까? 조금 주저하는 인원이 있지 않을까? 하는 생각도 들어서 익명으로 진행하였습니다~

> ## tbl_study_room & tbl_study_room_participant
> 방의 id와 이를 매핑애서 참가자 테이블이 있는 것 같은데 tbl_study_room에 있는 user는 방장이 되는건가요? 그렇다면 방장은 참가자 테이블에도 중복되서 들어가는지 궁금합니다.
- tbl_study_room에 있는 user는 방장이 되는 것이 맞습니다! 방장은 참가자 테이블에 중복되서 들어가지 않도록 할 생각입니다~

> 그리고 디자인을 보면 방마다 제목 이외에도 설명(ex: 네이버 기술면접 준비하는 방이에요~)이 들어있는데 description컬럼이 하나 들어가면 좋을 것 같아요.
- 아 그러네요 반영하겠습니다! :D

**Comment by Lavegaa** [comment]
익명으로 들어가는것은 병헌님이랑 의논 한번 해봐야 할 것같네요! 주저않고 리뷰를 남기는 측면에서는 좋은데 뭔가 피드백을 다른곳에 활용할 수 있지 않을까 해서요. 예를들면 방에 참가할 사람에 대해 그사람이 어떤 질문들을 남겨왔고?이런걸 보고 판단을 할 수 있다던지... 이건 의논 한번 해봐야 좋을 것 같아요.
